site_name: Nudge AI Docs
site_url: https://help.nudgeaiapp.com/
site_description: User guide and documentation for NudgeAI-email app on Shopify app store
site_author: NudgeAI Team

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - navigation.instant
  logo: assets/images/logo.svg
  favicon: assets/images/logo.svg
  palette:
    primary: indigo
    accent: yellow
  font:
    text: Helvetica
    code: Roboto Mono

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - footnotes
  - toc:
      permalink: true
      toc_depth: 2

nav:
  - Home: index.md
  - User Guide:
    - Overview: user-guides/overview.md
    - Initial Setup: user-guides/initial-setup.md
    - Settings: user-guides/settings.md
    - Use Cases: user-guides/use-cases.md
    - Pricing & Payment: user-guides/pricing-payment.md
    - Compliance: user-guides/compliance.md
  - Features:
    - Google One Tap Login: 
      - Overview: features/google-one-tap/index.md
      - Benefits: features/google-one-tap/benefits.md
      - How It Works: features/google-one-tap/how-it-works.md
      - Implementation: features/google-one-tap/implementation.md
      - Customization: features/google-one-tap/customization.md
      - Best Practices: features/google-one-tap/best-practices.md
      - FAQ: features/google-one-tap/faq.md
    - Smart Popups: 
      - Overview: features/smart-popups/index.md
      - Comparison: features/smart-popups/comparison.md
      - How It Works: features/smart-popups/how-it-works.md
      - Benefits: features/smart-popups/benefits.md
      - Customization: features/smart-popups/customization.md
      - Best Practices: features/smart-popups/best-practices.md
      - Success Stories: features/smart-popups/case-studies.md
      - FAQ: features/smart-popups/faq.md
  - Success Stories:
    - Overview: success-stories/index.md
    - E-commerce:
      - BOLT Clothing: success-stories/ecommerce-bolt.md
      - Iron Company: success-stories/ecommerce-iron.md
      - eBay: success-stories/ecommerce-ebay.md
    - Media & Content:
      - The Daily Post: success-stories/media-daily-post.md
      - Reddit: success-stories/media-reddit.md
      - Pinterest: success-stories/media-pinterest.md
    - SaaS & B2B:
      - TechFlow: success-stories/b2b-techflow.md
      - Zapier: success-stories/b2b-zapier.md
      - Trivago: success-stories/b2b-trivago.md
    - Real Estate & Travel:
      - Redfin: success-stories/travel-redfin.md
      - Hipmunk: success-stories/travel-hipmunk.md
  - Release Notes: release-notes.md
  - 개인정보 처리방침: privacy-policy.md
  - "Get the App ↗": https://apps.shopify.com/

plugins:
  - meta

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/external-links.js

extra:
  social:
    - icon: fontawesome/brands/shopify
      link: https://apps.shopify.com/
      name: NudgeAI on Shopify App Store
