site_name: Nudge AI Docs
site_url: https://nudge-ai-agent.github.io/
site_description: User guide and documentation for NudgeAI-email app on Shopify app store
site_author: NudgeAI Team

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
  icon:
    logo: material/email-plus
  font:
    text: Helvetica
    code: Roboto Mono

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - footnotes

nav:
  - Home: index.md
  - User Guide:
    - Overview: user-guides/overview.md
    - Initial Setup: user-guides/initial-setup.md
    - Settings: user-guides/settings.md
    - Use Cases: user-guides/use-cases.md
    - Pricing & Payment: user-guides/pricing-payment.md
  - Features:
    - Google One Tap Login: features/google-one-tap.md
    - Apple Sign In: features/apple-sign-in.md
    - AI-based Smart Popups: features/smart-popups.md
    - Dashboard: features/dashboard.md
  - Release Notes: release-notes.md
  - Privacy & Legal:
    - Privacy Policy: legal/privacy-policy.md
    - Terms of Service: legal/terms-of-service.md
    - Compliance: legal/compliance.md

plugins: []

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nudgeai
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/nudgeai
